  name: lint_workflow
  on:
    pull_request:
      branches:
        - main
  jobs:
    lint:
      name: Lint Code Base
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Set up lint
          uses: github/super-linter/slim@v4
          env:
            VALIDATE_ALL_CODE_BASE: true
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}