name: release_workflow
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build-release:
    permissions: write-all
    runs-on: ubuntu-latest

  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Release Go binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 1.21
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}


      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: "${{secrets.DOCKERHUB_USERNAME}}"
          password: "${{secrets.DOCKERHUB_TOKEN}}"
      - name: Setup docker build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{secrets.DOCKERHUB_USERNAME}}/exams_dvp:${{ github.ref_name}}"